version: "3.8"

services:
  backend:
    image: todo-app
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    expose:
      - "9000"
    volumes:
      - .:/var/www/app
    networks:
      - app-network

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mariadb:
    image: mariadb:10.7.1
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: app
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: app
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - mariadb:/var/lib/mariadb
    networks:
      - app-network

networks:
  app-network:

volumes:
  mariadb:
